// <auto-generated />
using System;
using FaturaWeb.Util;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FaturaWeb.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FaturaWeb.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Agencia")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Bairro")
                        .IsRequired();

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("char(9)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("char(14)");

                    b.Property<string>("Conta")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Fone")
                        .HasColumnType("char(12)");

                    b.Property<string>("InscMunicipal")
                        .HasColumnType("char(14)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeBanco")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("FaturaWeb.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClienteId");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("Date");

                    b.Property<int?>("EmissorId");

                    b.Property<string>("Empenho")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Numero");

                    b.Property<string>("Observacao");

                    b.Property<string>("TempoPrestacao");

                    b.Property<decimal>("ValorTotal");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmissorId");

                    b.ToTable("Faturas");
                });

            modelBuilder.Entity("FaturaWeb.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<int?>("FaturaId");

                    b.Property<int>("Quantidade");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("FaturaWeb.Models.Fatura", b =>
                {
                    b.HasOne("FaturaWeb.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("FaturaWeb.Models.Cliente", "Emissor")
                        .WithMany()
                        .HasForeignKey("EmissorId");
                });

            modelBuilder.Entity("FaturaWeb.Models.Item", b =>
                {
                    b.HasOne("FaturaWeb.Models.Fatura")
                        .WithMany("Itens")
                        .HasForeignKey("FaturaId");
                });
#pragma warning restore 612, 618
        }
    }
}
